-- [Task]: T-008
-- [From]: specs/database/schema.md §Table: users, plan.md §Part 1.2 (Database Initialization)
-- [Phase]: II (User authentication and account management)
-- [Purpose]: Create users table - foundation for multi-tenant authentication and user isolation

-- Drop table if exists (for idempotent re-runs in development)
DROP TABLE IF EXISTS users CASCADE;

-- Create users table with authentication and account data
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance optimization

-- Index 1: Fast email lookups (required for login operation)
-- Common query: SELECT * FROM users WHERE email = :email
CREATE INDEX idx_users_email ON users(email);

-- Index 2: Primary key (UUID) is implicitly indexed
-- Common query: SELECT * FROM users WHERE id = :user_id

-- Verify table created successfully
-- SELECT * FROM users LIMIT 0;  -- Returns empty result set with correct schema

-- Table Design Notes:
-- - id: UUID primary key generated by PostgreSQL (not sequential, globally unique)
-- - email: VARCHAR(255) UNIQUE enforces one account per email address
-- - password_hash: Bcrypt hash (60 chars + 195 buffer = 255 total)
-- - created_at: Account creation timestamp (UTC, immutable after creation)
-- - updated_at: Last modification timestamp (UTC, updated when user changes password/email)
-- - All columns NOT NULL ensures complete user records (no partial data)
-- - ON DELETE CASCADE will cascade to tasks and conversations tables (user deletion cleanup)
