-- [Task]: T-009, T-010
-- [From]: specs/database/schema.md §Table: tasks, plan.md §Part 1.2 (Database Initialization)
-- [Phase]: II (Task CRUD operations with user isolation)
-- [Purpose]: Create tasks table - user-scoped todo items with multi-tenant isolation

-- Drop table if exists (for idempotent re-runs in development)
DROP TABLE IF EXISTS tasks CASCADE;

-- Create tasks table with task data and user association
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tasks_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for performance optimization

-- Index 1: Fast filtering by user_id (required for user-scoped queries)
-- Common query: SELECT * FROM tasks WHERE user_id = :uid
CREATE INDEX idx_tasks_user_id ON tasks(user_id);

-- Index 2: Composite index for dashboard query pattern
-- Enables both filtering (user_id) and sorting (created_at DESC) efficiently
-- Common query: SELECT * FROM tasks WHERE user_id = :uid ORDER BY created_at DESC
-- This index covers the WHERE clause and the ORDER BY clause (index-only scan possible)
-- Satisfies SC-002 performance requirement (dashboard list < 1 second latency)
CREATE INDEX idx_tasks_user_id_created_at ON tasks(user_id, created_at DESC);

-- Verify table created successfully
-- SELECT * FROM tasks LIMIT 0;  -- Returns empty result set with correct schema

-- Table Design Notes:
-- - id: UUID primary key generated by PostgreSQL (not sequential, globally unique)
-- - user_id: UUID foreign key to users(id)
--   * NOT NULL enforces every task has an owner
--   * ON DELETE CASCADE automatically deletes user's tasks when user is deleted
--   * Indexed for fast user-specific lookups
-- - title: VARCHAR(255) NOT NULL, required task name (non-empty enforced at application layer)
-- - description: TEXT nullable, optional task details (no length limit)
-- - completed: BOOLEAN NOT NULL DEFAULT FALSE, task completion status
-- - created_at: Task creation timestamp (UTC, immutable after creation)
-- - updated_at: Last modification timestamp (UTC, refreshed on every edit)
-- - All non-nullable columns have explicit NOT NULL constraints
-- - Foreign key constraint prevents assigning task to non-existent user (referential integrity)
-- - Composite index (user_id, created_at DESC) enables fast dashboard queries:
--   1. Filters tasks by user_id (first index column)
--   2. Pre-sorts by creation date newest first (second index column DESC)
--   3. Covers both WHERE and ORDER BY clauses (index-only scan)
--   4. No additional sort operation needed for dashboard pagination
